# This is the Snakemake configuration file that specifies paths and 
# and options for the merge_callers pipeline. Anybody wishing to use
# the provided snakemake pipeline should first fill out this file with paths to
# their own data, as the Snakefile requires it.


# The path to a text file specifying where to find read information for each sample
# Each row in the sample file should represent a different sample.
# The sample file should have 3 columns (each separated by a single tab):
#       <unique_sample_name> <fastq1_path> <fastq2_path>
"sample_file" : "/iblm/netapp/home/amassarat/breakCA/merge_callers/samples.tsv"

# which samples should we execute the pipeline on?
# comment out this line if you want to run all samples
# "SAMP_NAMES" : ["SRR891269"]

# The path to a reference genome for BWA
"genome" : "/iblm/netapp/data1/external/GRC37/combined/bwa_index_assembly19/Homo_sapiens_assembly19.fasta"

# directory in which to output all of the output files
# defined relative to whatever directory you execute the snakemake command in
"output_dir" : "/iblm/netapp/home/amassarat/breakCA/merge_callers/out"

# which callers do you want to run to find SNVs?
# if you don't want to run the snp pipeline, set this to a falsey value or comment out the line
"snp_callers" : ["gatk-snp", "varscan-snp", "pg-snp"]

# which callers do you want to run to find indels?
# if you don't want to run the indel pipeline, set this to a falsey value or comment out the line
"indel_callers" : ["gatk-indel", "varscan-indel", "delly", "pindel", "manta", "strelka", "pg-indel"]

# what are the maximum number of threads to use for the entire pipeline?
"num_threads" : 8


# CALLER SPECIFIC PARAMETERS
# specify any parameters that should be passed to each caller script here
# key should be <caller_name>_params and value can be string or array of parameters

# manta parameters
# 1) path to manta config file
# 2) path to the directory in which manta is stored or "" if manta is installed in the conda env (ex: if using --use-conda)
"manta" : ["/iblm/netapp/home/amassarat/breakCA/merge_callers/scripts/configManta.py.ini", ""]

"delly_cols" : {"format":["RC", "CN", "GT", "GQ"]}

"pindel_cols" : {"info":["HOMLEN", "SVLEN", "SVTYPE", "NTLEN"], "format":["PL", "GT", "RD", "AD"]}

# strelka parameters
# 1) path to strelka config file
# 2) path to the directory in which strelka is stored or "" if strelka is installed in the conda env (ex: if using --use-conda)
"strelka" : ["/iblm/netapp/home/amassarat/breakCA/merge_callers/scripts/configureStrelkaGermlineWorkflow.py.ini", ""]

# platinum genomes parameters
# path to a bgzip, indexed VCF containing variants called in the platinum genomes project
"pg-snp" : "/iblm/netapp/data1/external/PlatinumGenomes/2017-1.0/hg19/hybrid/hg19.hybrid.no_chr.vcf.gz"
"pg-indel" : "/iblm/netapp/data1/external/PlatinumGenomes/2017-1.0/hg19/hybrid/hg19.hybrid.no_chr.vcf.gz"
