# This is the Snakemake configuration file that specifies paths and 
# and options for the classify pipeline. Anybody wishing to use
# the provided snakemake pipeline should first fill out this file with paths to
# their own data, as the Snakefile requires it.
# Note: this file is written in the YAML syntax (https://learnxinyminutes.com/docs/yaml/)


# DATASETs
# the dataset should be named by a unique id
# for each dataset, you must provide
#   1) path - The path to the dataset in .tsv.gz format
#      Each row must represent a position in the genome, and each column a feature to train on
#      The first two columns must be "CHROM" and "POS", in that order
#      All REF and ALT columns in the table must be prefixed by the caller they belong to, followed by a tilde "~", and either "REF" or "ALT"
#   2) truth - The truth caller id in the dataset
#      This is only required if the dataset will be used for training data
#      If you provide this attribute for a prediction dataset, the dataset will be used as a test set
#   3) filter - (optional) A list of filtering expressions for filtering the data before training or testing
#      A filtering expression consists of the following concatenated together:
#          - the name of the column in the table upon which to filter
#          - one of any of awk's comparison operators (ex: >, <, ==)
#          - a value to filter on
#      The order of the filtering expressions must match the order of the cols in the TSV.
data:
  SRR891269:
    path: data/indel.tsv.gz # this is the platinum genomes training data!
    truth: &truth
      pg-indel
    filter: &filter
      - 'gatk-indel~DP>10'
  # here is an example test sample, but you can replace this with whichever
  # sample for which you'd like to predict variants::
  SRR891269_even:
    path: data/even-indels.tsv.gz
    truth: *truth # use the same truth column names as the SRR891269 training data
    filter: *filter # use the same filtering expressions, too

# The unique id of the training set to be used for training the classifier
train: SRR891269

# If you already have an RDA file containing a trained classifier, you can provide the path to it here.
# If this parameter is provided, the training step will not be performed and the training sample will be ignored.
# But if this parameter is commented out, the training step will be performed as usual.
model: data/indel.rda

# A list of samples for which to make predictions, identified by their unique sample id
# You may optionally specify a truth set for each sample if you want it to serve as test data (see "data" above)
predict: [SRR891269_even]

# Whether to perform cross validation in order to tune hyperparameters of the classifier
# Enabling this option will substantially increase the runtime of the pipeline
tune: false

# If you'd like the pipeline to create a plot of precision-recall curves, specify
# the column names to use for thresholding here. Otherwise, comment out these lines.
# Only single point precision-recall calculations will be performed for
# column names that don't have a value
# Prefix the column name with a * if it should be sorted in reverse order
prcols:
  gatk-indel: QD
  '*varscan-indel': PVAL
  vardict-indel: QUAL
  pindel:
  delly:
  illumina-manta: QUAL
  illumina-strelka: QUAL

# The path to the directory in which to place all of the output files
# defined relative to whatever directory you execute the snakemake command in
out: out/classify
